services:
  magizhchi:
    platform: linux/arm64/v8
    build:
      context: .
      dockerfile: .build/Dockerfile
      network: host
      args:
        USER_NAME: ${USER_NAME}
        UID: ${CURRENT_UID}
        GID: ${CURRENT_GID}
        OCAML_COMPILER: ${OCAML_COMPILER}
    image: localhost:5000/magizhchi
    container_name: magizhchi-${USER}
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ${MODELS_DIR}
        target: /home/${USER_NAME}/magizhchi
      - type: bind
        source: /etc/passwd
        target: /etc/passwd
        read_only: true
      - type: bind
        source: /etc/group
        target: /etc/group
        read_only: true
      - type: bind
        source: /etc/shadow
        target: /etc/shadow
        read_only: true
    user: ${CURRENT_UID}:${CURRENT_GID}
    ports:
      - "127.0.0.1:${PORT}:8421"
    shm_size: 2gb
